general:
    experiment_name: l2_gan
data:
    data_path: './data/modis_ndvi_processed/aggregated/96_sampled_125.npz'
model:
    model_name: sr_gan
    generator_blocks: 8
train:
    num_epochs: 50
    content_loss: 'l2'
    gan_loss_scale: .001
    use_gan_loss: True
    batch_size: 16
    learning_rate: .0001
    device: 'cuda:0'
results:
    overwrite: True

