general:
    experiment_name: 'non_gan_edge_loss'
data:
    data_path: './data/modis_ndvi_processed/aggregated/96_sampled_002.npz'
model:
    model_name: sample_gan
    generator_blocks: 4
train:
    num_epochs: 40
    content_loss: 'edge_loss'
    content_loss_scale: 1.
    use_gan_loss: False
    batch_size: 16
    learning_rate: 0.0001
    vgg_layer: 8
    threshold: 1
    edge_loss_coef: 0.01
results:
    overwrite: True
    results_dir: 'results/'
