general:
    experiment_name: siamese_gan
data:
    data_path: './data/modis_ndvi_processed/aggregated/96_sampled_125.npz'
model:
    model_name: siamese_gan
    generator_blocks: 8
train:
    num_epochs: 100
    content_loss: 'None'
    gan_loss_scale: .001
    gan_loss: 'siamese'
    use_gan_loss: True
    batch_size: 16
    learning_rate: .0001
    device: 'cuda:0'
results:
    overwrite: False
    model_name: sample_gan
    generator_blocks: 4
